name: Craftista

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install npm packages
        working-directory: ./frontent
        run: npm ci

      - name: Build
        working-directory: ./frontent
        run: npm run build --if-present

      - name: Run test
        working-directory: ./frontent
        run: npm test
